# Generated by Django 4.2.11 on 2024-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE_DETAILS',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.TextField(blank=True)),
                ('emp_age', models.IntegerField()),
            ],
        ),
    ]
